name: generate-snake-game-from-github-contribution-grid
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2.0.0-rc.2
