name: generate-snake-game-from-github-contribution-grid
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: generate-snake-game-from-github-contribution-grid
        uses: Platane/snk@v2
        with:
          github_user_name: lx78WyY0J5
    outputs: |
      dist/github-snake.svg
      dist/github-snake-dark.svg?palette=github-dark
